---
- hosts: localhost
  vars_files:
        - users.yml
  tasks:
        - name: newuser creation
          vars:
             password: "{{ lookup('password', '' './password-{{ item.name }}' ' length=6') }}"
          user: 
             name: "{{ item.name }}"
             uid:  "{{ item.uid }}"
             comment: "{{ item.name | capitalize }} {{ item.last | capitalize }}"
             password: "{{ password | password_hash('sha512') }}"
             update_password: on_create
          with_items:
               - "{{ myusers }}"

